"""Add amount_repaid column to loans

Revision ID: d86e2d75bc0e
Revises: 
Create Date: 2026-02-17 12:56:04.809316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86e2d75bc0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('amount_repaid', sa.Float(), nullable=True))
    op.execute("UPDATE loans SET amount_repaid = 0.0 WHERE amount_repaid IS NULL")
    op.alter_column('loans', 'amount_repaid', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'amount_repaid')
    # ### end Alembic commands ###
